### PR TITLE
Xray markers

### PR DESCRIPTION
**Pull request by vidartf**
Adds (a somewhat crude) support for X-ray line markers.

### CODE REVIEW

**Comment by pburdet** [comment]
Great! It works. There is a bug. If you select marker, then the spectrum disappear from the data view and you cannot call the element windows any more

**Comment by pburdet** [comment]
Sorry, I was not working with the latest version of your "work_house" branch. It works now

**Comment by vidartf** [comment]
Oh yeah, I modified the plot code a bit to not plot if a plot was currently
active, but I guess I should also handle possible replots.

**Comment by vidartf** [comment]
Mixed on master.

**Pull request merged**
