### PR TITLE
Fixing icon text and centering

### LINKED ISSUE #16: Mangled Toolbar icons on Linux
As I was playing around with HyperspyUI today on my laptop, I noticed that some icons didn't look as expected, and were cut off on the edges, namely the text ones (see below).

icon_snapshot1

After playing around with this, I discovered that it is due to the Calibri font (which is saved in the .svg files) is not present on Linux, so the font gets substituted in a less than ideal manner.

Searching around online, there are a few options for fixing this and having a truly "cross-platform" font. The font can be embedded in the qt resources, but this seems like it is an undesirable setup. The other option would be to either convert all the text entries in the .svg files to paths (so there is no text rendered by qt), or to use a font that is very likely to be present on all systems.

### PR DESCRIPTION
**Pull request by jat255**
This PR resolves #16. 

I went through all of the icons and replaced all the references to Calibri to Arial text objects (since Arial should be fairly ubiquitous on all platforms). This fixed the display on my system. I also touched up a few icons where I thought it looked better (but these are just suggestions). Finally, the `tightlayout` plugin had an absolute icon path present, so I fixed that. Here's the before and after on my system:

icon_snapshot_before_after

You can see the PCA and BSS icons look better, as do all the FFT ones. I also changed the `NFFT` to `Sig. FFT`, because I think that's more clear, but we can certainly keep it as `NFFT`.

### CODE REVIEW

**Comment by jat255** [comment]
I also just tested this solution on my Windows machine at work, and it seems good!

icon_snapshot_windows

**Comment by vidartf** [comment]
What software did you use to save the SVGs? I saved from Adobe Illustrator, and checked to "embed used symbols"), which means that the letters used are supposed to be embedded into the file. You can see it as the "glyph" tags I think. I think the clipping might be because of incorrect handling of these.

I see you also changed the linewidth of several lines in some of the icons. was this intentional?

PS: I see you have a rather dark background on your linux machine; do you normally render icons in black, or is that an issue as well?

**Comment by jat255** [comment]
> What software did you use to save the SVGs?

I used Inkscape (since I was on my laptop), which I should hope is the most "compliant" solution. I would think the Illustrator solution would work as well, but I guess not...

> I see you also changed the linewidth of several lines in some of the icons. was this intentional?

The linewidths changed because I converted the lines to strokes, rather than paths. The actual thickness was rather unintentional, but now can be easily changed just using the stroke width parameter, rather than altering the path. I can make them thicker, if you'd prefer.



> PS: I see you have a rather dark background on your linux machine; do you normally render icons in black, or is that an issue as well?

I do have a dark background, and this was something I was going to bring up as well, but I figured it's of limited importance compared to other things :smile: I was thinking of duplicating all the icons in a lighter color, and then maybe we could add an option to the settings dialogue that would allow users to switch between dark and light icons. I figure there must be some way to detect the background color, but I'd have to look into that more.

**Comment by jat255** [comment]
New line thicknesses:

fourier_ratio    gaussian power_law

**Comment by vidartf** [comment]
> I was thinking of duplicating all the icons in a lighter color,

I was thinking more along the lines of trying to figure out if there is a way to have the icons use the system foreground color (white on your system I assume?).

**Comment by jat255** [comment]
Yes, that's a better idea.

After some searching, I figured out that you can get the current text color with `app.palette().color(QtGui.QPalette.Text).getRgb()`. On my Windows system, this returns black, as expected, and on my KDE, it shows the light gray that is my default text color.

Now the question is rendering the SVGs. Since they are text files, perhaps we could just run a text replacement on them before importing them? Or maybe there's a better way to change the colors. I'll look around.

**Comment by jat255** [comment]
So here's an example that's working. Forgive how incredibly ugly the code is, as I am just hacking my way through learning some Qt for the first time...

icon_color_testing


Basically, the magic happens in a method that loads the .svg code , finds the designation of black, and changes it to whatever color you want, writing a tempfile containing the new color. You can see in the example that it doesn't always work though. Since the default color for a stroke is black, Inkscape does not necessarily write that information in. This method will be somewhat sensitive to how we create our icon files, but I believe it should work assuming we're consistent in that regard. For the example, I've changed the color to `'red'`, but you can get the foreground text color like I commented before and use that.

I wrote up this example to show how this is currently running on all of the icon files. As you can see, it works on some, but not all. To get it working on all, I think it would be easiest to save the .svg files as some other color, and then replace the color _en masse_.

I was also reading about how you can recolor and SVG with a renderer on the fly, but I couldn't really get that to work, and it required painting an svg onto a QImage and QPixmap to get it into an icon, which seems much clunkier than this solution.

What do you think of this? I'll hold off on going through and fixing the .svg files until I hear from you.

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Based off of:

ZetCode PyQt4 tutorial 

This program creates a skeleton of
a classic GUI application with a menubar,
toolbar, statusbar and a central widget. 

author: Jan Bodnar
website: zetcode.com 
last edited: September 2011
"""

import sys
from PyQt4 import QtGui
import tempfile, glob, os


class Example(QtGui.QMainWindow):
    
    def __init__(self):
        super(Example, self).__init__()
        
        self.initUI()
        
    def replaceSvgColor(self, filename, oldColor, newColor):
        '''
        Generate and return a temp svg filename with oldColor replaced
        by newColor (color names are in HTML format '#XXXXXX')
        '''
        svg_file = open(filename, 'r')
        svg_cnt = svg_file.read()
        temp = tempfile.NamedTemporaryFile(delete=False)
        temp.write(svg_cnt.replace(oldColor, newColor))
        temp.close()
        
        return temp.name
        
    
    def initUI(self):     
        stack = QtGui.QVBoxLayout()        
        widget = QtGui.QWidget()
        
        color_list = []
        color_list.append(('QtGui.QPalette.Window', 
                           self.palette().color(QtGui.QPalette.Window)))
        color_list.append(('QtGui.QPalette.Background', 
                           self.palette().color(QtGui.QPalette.Background)))
        color_list.append(('QtGui.QPalette.WindowText', 
                           self.palette().color(QtGui.QPalette.WindowText)))
        color_list.append(('QtGui.QPalette.Foreground', 
                           self.palette().color(QtGui.QPalette.Foreground)))
        color_list.append(('QtGui.QPalette.Base', 
                           self.palette().color(QtGui.QPalette.Base)))
        color_list.append(('QtGui.QPalette.AlternateBase', 
                           self.palette().color(QtGui.QPalette.AlternateBase)))
        color_list.append(('QtGui.QPalette.ToolTipBase', 
                           self.palette().color(QtGui.QPalette.ToolTipBase)))
        color_list.append(('QtGui.QPalette.ToolTipText', 
                           self.palette().color(QtGui.QPalette.ToolTipText)))
        color_list.append(('QtGui.QPalette.Text', 
                           self.palette().color(QtGui.QPalette.Text)))
        color_list.append(('QtGui.QPalette.Button', 
                           self.palette().color(QtGui.QPalette.Button)))
        color_list.append(('QtGui.QPalette.ButtonText', 
                           self.palette().color(QtGui.QPalette.ButtonText)))
        color_list.append(('QtGui.QPalette.BrightText', 
                           self.palette().color(QtGui.QPalette.BrightText)))
        
        textEdit = QtGui.QTextEdit()
        for n, c in color_list:
            textEdit.append(n + ':\t' + str(c.name()))
        stack.addWidget(textEdit)
        
        # Change this to wherever your icons are stored
        icon_files = glob.glob("D:/UMD_Research/Software/hyperspyUI/"
                               "hyperspyui/images/*.svg")        
                        
        widget.setLayout(stack)
        self.setCentralWidget(widget)

        toolbar1 = self.addToolBar('Bar1')
        toolbar2 = self.addToolBar('Bar2')
        toolbar3 = self.addToolBar('Bar3')
        
        ico_list = [''] * len(icon_files)      
        action_list = [''] * len(icon_files)      
        for i, f in enumerate(icon_files):        
            ico_list[i] = QtGui.QIcon(self.replaceSvgColor(f, 
                                                           '#000000', 
                                                           'red'))
            action_list[i] = QtGui.QAction(ico_list[i], 'Exit', self)
            action_list[i].setStatusTip(os.path.basename(f))
            

            # add to toolbars
            if i/float(len(icon_files)) <= 0.33:            
                toolbar1.addAction(action_list[i])
            elif i/float(len(icon_files)) <= 0.66:
                toolbar2.addAction(action_list[i])
            else:
                toolbar3.addAction(action_list[i])

        # shortcut to close ('X' icon in position 8)
        action_list[8].setShortcut('Ctrl+Q')
        action_list[8].triggered.connect(self.close)

        self.insertToolBarBreak(toolbar2)
        self.insertToolBarBreak(toolbar3)

        self.statusBar()

        menubar = self.menuBar()
        fileMenu = menubar.addMenu('&File')
        fileMenu.addAction(action_list[8])
        
        self.setGeometry(300, 300, 650, 350)
        self.setWindowTitle('Icon color testing')    
        self.show()

        self.statusBar().showMessage("Ready")

        
        
def main():
    
    app = QtGui.QApplication(sys.argv)
    _ = Example()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()    
```

**Comment by jat255** [comment]
And here's what it looks like on my Linux system (using `color_list[-4][1].name()` (the text color) instead of 'red'):

icon_snapshot_after1

To me, this seems to be a good strategy. We'll just have to make sure the icons are formatted correctly.

**Comment by vidartf** [comment]
Heh, I made a fix for this as well. Mine's based on an implementation of `QIconEngineV2`, and basically only works with simple monochrome images like that used already. I like the features of yours better since it handles multiple colors, but the temporary files feels like quite a hack, and I'm not sure why only some of the black is replaced?

If we combine your code and mine, we can get rid of the temporary files, since in the implementation of  `QIconEngineV2` we interface directly to `QSvgRenderer`, which can then take either a `QByteArray` or a `QXmlStreamReader`.

How mine looks (in window's ugly high contrast mode):
mono_icons

**Comment by vidartf** [comment]
Using `QXmlStreamReader` would also allow us to edit the colors in a more informed way if necessary (e.g. by tags/IDs).

**Comment by jat255** [comment]
So the reason only some of the colors were replaced is because they were not explicitly defined as "#000000" in the .svg files. I went through and added an explicit style to each one, and here's what I get:

icon_color_testing2

**Comment by jat255** [comment]
And I suppose the temporary file thing is a bit hackish, although it's fairly quick and simple, and doesn't create too much overhead (although I'm not sure how it would compare to using `QXmlStreamReader`) to do the same thing.

**Comment by vidartf** [comment]
Putting your code as the "engine" in the `QIconEngineV2` was quite easy. Now I use it in a function like this:
```python
def _replace_in_stream(self, filename):
    svg_file = open(filename, 'r')
    svg_cnt = svg_file.read()
    for old, new in self._color_replacements.iteritems():
        svg_cnt = svg_cnt.replace(old, new)
    out = QByteArray(svg_cnt)
    return out
```
I'm going to check whether the SVG reader in Qt supports CSS, cause if it does I think the smartest solution could be to inject some CSS at the start of the document.

**Comment by jat255** [comment]
Oh, cool. I guess that's not too much more difficult. Does that edit the actual file?

**Comment by vidartf** [comment]
No, but I think it might end up holding the edited file in memory. As SVG files are quite small that shouldn't be an issue.

**Comment by vidartf** [comment]
Never mind that last point: Actually, whenever it needs to recreate an icon, it reads the original file, changes the content on the fly, and then creates the icon from that new version.

**Comment by jat255** [comment]
Oh, I think I see it now. The new engine will accept a stream of data, and then we just use that instead. Makes sense.

**Comment by vidartf** [comment]
I did a manual merge from here. Could you please check that everything works as expected?

**Comment by jat255** [comment]
It looks good on my Windows machine, but I just tested on a linux vm, and it still looks weird. I'm investigating more...

**Comment by vidartf** [comment]
Note that I'm using the foreground color instead of the text color. I don't
know if that might be it?

**Comment by jat255** [comment]
I saw that. It appears to be looking alright on my laptop, so I'm not sure why it wasn't looking right on my VM (they're both Arch running KDE...). The only thing I notice off-hand is that the "disabled" color looks to be the same as the "active" color, so it is hard to tell what is active vs. not when viewing on the dark background.

Here's `foreground()`:
foreground_icons

And here's `text()`:
text_icons

Just for kicks, here's `windowText()` as well (seems to be same as `foreground()`:
windowtext_icons

Personally, I think `text()` looks the best as it provides the best contrast. This could vary depending on themes, of course. Also, in the [qPalette documentation](http://doc.qt.io/qt-4.8/qpalette.html), they say that `foreground` is deprecated, so it may be best to use either `windowText()` or `text()`.

**Comment by jat255** [comment]
Nevermind the comment about the VM. It's working correctly too. I had an old copy of HyperspyUI installed through `pip`. Once I updated it to the git version, it was working as expected.

**Comment by jat255** [comment]
As for the disabled colors, I suppose this is a bit tricky. We want them to get darker (I presume) if you have a dark background, and lighter on a light BG (as they currently do).

**Comment by vidartf** [comment]
With the IconEngine I think we can override the default color fade. I would
assume the default solution is to fade it closer to the background color
(add some alpha simply?).

**Comment by jat255** [comment]
Yeah, I was looking online, and in their style guide, google says that

"Hint and disabled text and icons have an opacity of 26% for dark text on
light backgrounds, and an opacity of 30% for white text on dark
backgrounds."

So perhaps if we change the color to alpha = 0.3, that would be sufficient?
I'm not sure how to do that though, sorry.

**Comment by jat255** [comment]
BTW, there's a missing comma at https://github.com/vidartf/hyperspyUI/blob/master/hyperspyui/smartcolorsvgiconengine.py#L40

**Comment by vidartf** [comment]
> there's a missing comma

Thanks for pointing it out. That's what you get for trying to finish up in a hurry.

For disabled text, I think maybe it will be better to use the foreground color of `QPalette.Disabled`. Hopefully that is set from the system's styles.

**Comment by vidartf** [comment]
Newest commits to master use WindowText, and correctly applies `QPalette.Disabled`. Also, now it should update the icons if the application palette changes, so you can do this:
```python
from PyQt4.QtGui import QApplication, QPalette, QColor
from PyQt4.QtCore import Qt
p = QApplication.palette()
p.setColor(QPalette.WindowText, QColor(Qt.red))
p.setColor(QPalette.Disabled, QPalette.WindowText, QColor(Qt.blue))
QApplication.setPalette(p)
```
This should allow for easy testing, and means icons will also be updated if a palette editor is implemented in the future.

**Comment by jat255** [comment]
Cool! This looks a lot better. For reference, I tried  it out on a bunch of different themes on my laptop:

1-icons_dark3
1-icons_dark4
1-icons_light

Some are better than others, but on the whole I think it is much clearer what is disabled vs. not in the dark schemes.

Here are a couple examples using `Text` instead of `WindowText`, as well (note, I'm not sure if I chose the same themes, so they might not be directly comparable to the above):
2-icons_dark - with text
2-icons_dark2 - with text
2-icons_light - with text

It doesn't look like it makes a huge difference, so `WindowText` is probably fine.

**Pull request merged**
